create table employee (
    id integer generated by default as identity,
    age integer,
    company_id integer,
    gender varchar(255),
    name varchar(255),
    salary integer,
    primary key (id)
)
